### ISSUE TITLE
star rating

### ISSUE THREAD

**Issue by joshmorel** [chingu-coders/Voyage2-Bears-04#24]
Create the component for star rating and backend for saving it

**Comment by ReeceLangerock** [comment]
component for star rating exists and is 95% completed. Basically just needs handling for saving to backend.

**Comment by joshmorel** [comment]
I've made progress on this [branch](https://github.com/chingu-coders/Voyage2-Bears-04/tree/feature/rating-backend) getting both front-end (needed to make some changes, among other things clearStars went to zero even if rating already exists) and back-end working together mostly now but want to get feedback on a few items before finishing off.

## Optimistic Update Approach

This applies to both rating and also changing status and perhaps other items later.

* [ ] Should we use a library (redux-optimistic-ui) or at come up with a consistent best practice approach? The current WIP is just updating state locally & dispatching HTTP action (have not yet addressed failures) but I don't think this is best practice.
* [ ] From UI perspective, for success, do we want to provide any confirmation feedback (like extra temporary highlighting)?
* [ ] For failure - we want to show something but what, a little popup?

## Other Decisions

* [ ] Clearing rating. I got this working, but should it be displayed by default? I think yes. But I think conditionally to if there exists a rating by that user already
* [ ] Currently, if not logged in, I hid the 2 columns (status & rating). Is this good? Another option is to give user a login option if someone tries to rate (like IMDB) but I think this can wait.

**Comment by ReeceLangerock** [comment]
I hadn't thought about best practives for updating this and things like a users status of a resource. Taking a brief look at redux-optimistic-ui it looks like a good solution both technically and from a ui perspective.

### Optimistic Update Approach
* for success feedback, I do like how goodreads does it. Replaces the stars with "saving..." and on success pops up a small modal above it with a success message and a prompt to write a review as well. Fairly simple and gets the point across. 
* For failure, same as above but modal text and style says failure and the star can go back to empty.

### Other Decisions
* my thought on this was by default it shouldn't display, because in most cases the star rating will be presentational or for a resource the user hasn't yet rated. If it is a resource the user has rated then to display the option.
* Yep this is good, that was what my original plan for it was.

**Comment by joshmorel** [comment]
Okay. I'll keep going with this feedback in mind. 

Not unusually, not as straight forward as initially imagined!

**Comment by joshmorel** [comment]
I've been developing more understanding of MongoDB/mongoose and while an associative embedded array is nice for ease-of-querying it seems to be an [anti-pattern from storage perspective](https://github.com/JKHeadley/rest-hapi/#many_many-data-storage) because it is an array which grows without bounds.

This isn't a big deal for us now BUT because of [mongoose virtuals](http://thecodebarbarian.com/mongoose-virtual-populate) putting this into a separate associative linking collection (e.g. Resource-User) means this info is easy to query while enabling MongoDB best practices.

I'm going to work on seeing how this can work this weekend. I should have a PR to review with what seems best after experimentation.

**Comment by joshmorel** [comment]
Resolved by #43
