### ISSUE TITLE
naming conventions for resourceModel

### ISSUE THREAD

**Issue by ReeceLangerock** [chingu-coders/Voyage2-Bears-04#34]
Below is what I propose we revise the resourceModel to. Let me know thoughts, will have to make changes on both client and server

		title: String,
		url: String,
		imageUrl: String,
		description: String,
		difficulty: String,
		category: String,
		subcategory: String,
		cost: String,
		sale: { type: Boolean, default: false },
		ratings: [
			{
				ratedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'user' },
				rating: Number,
				_id: false
			}
		],
		reviews: [
			//objectID of review document
		],
		addedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'user' },
		brokenLink: [String],
		flaggedInappropriate: [String]
	}

**Comment by joshmorel** [comment]
All of these seem good with two question and one discussion point.

The first:

* `resourceComments` - would this not be resourceReviews?
* `brokenLink`/`flaggedInappropriate` - how will this be implemented, like basically, what is the String?

For ratings, so far in my work I've played around a bit with the underlying implementation, but when resource is queried what the output will be will include `rating` for the current user instead of the `ratings` array. We'd probably want to also return total ratings and average rating per resource. We could call this `ratingsCount`, `ratingsAvg`. Does this make sense? Alternately we could return `ratingsSum` with `ratingsCount` and calculate average on the client.

**Comment by ReeceLangerock** [comment]
* Yep, resourceComments should be actually just be reviews forgot to change that from the previous model
* `brokenLink`/`flaggedInappropriate` - This was a mistake, should be ObjectID. Thought was to store the ObjectIDs of users that had reported it although it could store more data if needed obviously.

Previously, I was using the array or rating objects to calculate the total and average. If we keep ratings included in the `resourceModel` we could stick with that but that's the kind of thing that could get messy if a resource ended up with a lot of ratings.
If we go the route of combining the rating with the review document then it would make sense to replace that field with `ratingsCount` and `ratingsAvg`.
